<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                           => __DIR__ . '/Module.php',
    'Application\Factory\IndexControllerFactory'   => __DIR__ . '/src/Application/Factory/IndexControllerFactory.php',
    'Application\Factory\TestTableGatewayFactory'  => __DIR__ . '/src/Application/Factory/TestTableGatewayFactory.php',
    'Application\Factory\MartandFormFactory'       => __DIR__ . '/src/Application/Factory/MartandFormFactory.php',
    'Application\Factory\MartandFormFilterFactory' => __DIR__ . '/src/Application/Factory/MartandFormFilterFactory.php',
    'Application\Form\MartandForm'                 => __DIR__ . '/src/Application/Form/MartandForm.php',
    'Application\Form\MartandFormFilter'           => __DIR__ . '/src/Application/Form/MartandFormFilter.php',
    'Application\Model\BackendTrait'               => __DIR__ . '/src/Application/Model/BackendTrait.php',
    'Application\Model\TestTableGateway'           => __DIR__ . '/src/Application/Model/TestTableGateway.php',
    'Application\Controller\IndexController'       => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Entity\Testtable'                 => __DIR__ . '/src/Application/Entity/Testtable.php',
);
