<?php

if (empty($data)) {
    
    $form->setAttributes(['method' => 'POST']);
    
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formcollection($form);
    echo $this->form()->closeTag();
    
}
else {
    
    $personId = $person['id'];
    
    $url = $this->url('home', [], ['query' => ['person' => $personId,]]);
    
    echo "<h1>Congratulations, <a href=\"$url\">{$person['name']}</a>!</h1>  <p><br /><br /><b>You are now a subscriber!  Your id is {$person['id']}</b></p>";
    
}